name: Integration Tests

on: [pull_request, push]

jobs:
  fprime-integration:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        fprime-version: [NASA-v1.5.3, v2.0.0, v3.0.0, devel]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip urllib3 setuptools_scm
          pip install -e .
      - name: clone fprime
        run: |
          git clone -b ${{ matrix.fprime-version }} https://github.com/nasa/fprime.git
          pip install fprime/
      # 0x72ad3277 is Fw/Types/Assert.cpp, a file that should be consistent across releases
      - name: Test generation and building on Ref
        working-directory: fprime/Ref
        run: |
          fprime-util generate
          fprime-util build
          fprime-util hash-to-file 0x72ad3277
      - name: Test special generation on Ref
        working-directory: fprime/Ref
        run: |
          fprime-util generate --build-cache ./special-cache --ut -DFPRIME_ENABLE_AUTOCODER_UTS=OFF
          fprime-util build --build-cache ./special-cache
          fprime-util hash-to-file 0x2ed4bda6 --build-cache ./special-cache
